export const mockUser = {
  id: "user_1",
  name: "John Doe",
  email: "john@example.com",
  image: null,
  isPro: false,
};

export const mockItemTypes = [
  { id: "type_snippet", name: "Snippet", icon: "Code", color: "#3b82f6", isSystem: true },
  { id: "type_prompt", name: "Prompt", icon: "Sparkles", color: "#8b5cf6", isSystem: true },
  { id: "type_command", name: "Command", icon: "Terminal", color: "#f97316", isSystem: true },
  { id: "type_note", name: "Note", icon: "StickyNote", color: "#fde047", isSystem: true },
  { id: "type_file", name: "File", icon: "File", color: "#6b7280", isSystem: true },
  { id: "type_image", name: "Image", icon: "Image", color: "#ec4899", isSystem: true },
  { id: "type_link", name: "Link", icon: "Link", color: "#10b981", isSystem: true },
];

export const mockCollections = [
  {
    id: "col_1",
    name: "React Patterns",
    description: "Common React patterns and hooks",
    isFavorite: true,
    itemCount: 12,
  },
  {
    id: "col_2",
    name: "Python Snippets",
    description: "Useful Python code snippets",
    isFavorite: false,
    itemCount: 8,
  },
  {
    id: "col_3",
    name: "Context Files",
    description: "AI context files for projects",
    isFavorite: true,
    itemCount: 5,
  },
  {
    id: "col_4",
    name: "Interview Prep",
    description: "Technical interview preparation",
    isFavorite: false,
    itemCount: 24,
  },
  {
    id: "col_5",
    name: "Git Commands",
    description: "Frequently used git commands",
    isFavorite: true,
    itemCount: 15,
  },
  {
    id: "col_6",
    name: "AI Prompts",
    description: "Curated AI prompts for coding",
    isFavorite: false,
    itemCount: 18,
  },
];

export const mockItems = [
  {
    id: "item_1",
    title: "useAuth Hook",
    description: "Custom authentication hook for React applications",
    contentType: "text",
    content: "export function useAuth() {\n  // auth logic\n}",
    itemTypeId: "type_snippet",
    isFavorite: true,
    isPinned: true,
    tags: ["react", "auth", "hooks"],
    collectionIds: ["col_1"],
    createdAt: "2026-01-15",
  },
  {
    id: "item_2",
    title: "API Error Handling Pattern",
    description: "Fetch wrapper with exponential backoff retry logic",
    contentType: "text",
    content: "async function fetchWithRetry(url, options, retries = 3) {\n  // retry logic\n}",
    itemTypeId: "type_snippet",
    isFavorite: false,
    isPinned: true,
    tags: ["api", "error-handling"],
    collectionIds: ["col_1"],
    createdAt: "2026-01-15",
  },
  {
    id: "item_3",
    title: "Python List Comprehension",
    description: "Common list comprehension patterns",
    contentType: "text",
    content: "squares = [x**2 for x in range(10)]",
    itemTypeId: "type_snippet",
    isFavorite: false,
    isPinned: false,
    tags: ["python", "lists"],
    collectionIds: ["col_2"],
    createdAt: "2026-01-10",
  },
  {
    id: "item_4",
    title: "Code Review Prompt",
    description: "Prompt for thorough code reviews",
    contentType: "text",
    content: "Review this code for bugs, performance issues, and best practices...",
    itemTypeId: "type_prompt",
    isFavorite: true,
    isPinned: false,
    tags: ["code-review", "ai"],
    collectionIds: ["col_6"],
    createdAt: "2026-01-08",
  },
  {
    id: "item_5",
    title: "git rebase workflow",
    description: "Interactive rebase for clean commit history",
    contentType: "text",
    content: "git rebase -i HEAD~3",
    itemTypeId: "type_command",
    isFavorite: false,
    isPinned: false,
    tags: ["git", "rebase"],
    collectionIds: ["col_5"],
    createdAt: "2026-01-05",
  },
  {
    id: "item_6",
    title: "Project context file",
    description: "Main AI context file for this project",
    contentType: "file",
    fileUrl: null,
    fileName: "context.md",
    fileSize: 4096,
    itemTypeId: "type_file",
    isFavorite: false,
    isPinned: false,
    tags: ["context", "ai"],
    collectionIds: ["col_3"],
    createdAt: "2026-01-03",
  },
];

export const mockItemTypeCounts = {
  snippet: 24,
  prompt: 18,
  command: 15,
  note: 12,
  file: 5,
  image: 3,
  link: 8,
};
